Add a versioned dependency on statsmodels for travis CI (#625)
* Add a versioned dependency on statsmodels for travis CI

New statsmodels 0.11.0 package seems to cause compatibility issues with older packages:

  RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

We depend on statsmodels 0.9.0 because this is the first version available on conda
for Python 3.5, 3.6 and 3.7, but users can use 0.8.0 as well.

Fix ar_coefficient method with newest statsmodels, AR class is now immutable.

Also latest dask requires fsspec in order to read data from disk.

* Move the ffspec requirement into the requirements.txt by requiring dask[dataframe]

Co-authored-by: Nils Braun <nils-braun@users.noreply.github.com>