pytest-3.0.4 upgrade
pytest-3.0.4 was released today, seeing as I am in tsfresh land verifying one or
two things and in test mode, I figured why not validate for you.

All tests run OK at current master (commit 8048ef44cc176ae46176573d9a4e83233a42c0d7)
on boh 2.7.12 and 3.5.2

### Python 2.7.12

OK

```
cd /opt/python_virtualenv/projects/tsfresh-py2712/
source bin/activate
bin/pip2.7 install --upgrade pytest
cd apps/blue-yonder_master/tsfresh/
git log | head
../../../bin/python2.7 setup.py test


gary@mc11:~$ cd /opt/python_virtualenv/projects/tsfresh-py2712/
gary@mc11:/opt/python_virtualenv/projects/tsfresh-py2712$ source bin/activate
(tsfresh-py2712) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py2712$ bin/pip2.7 install --upgrade pytest
Collecting pytest
  Downloading pytest-3.0.4-py2.py3-none-any.whl (170kB)
    100% || 174kB 523kB/s
Requirement already up-to-date: py>=1.4.29 in ./lib/python2.7/site-packages (from pytest)
Installing collected packages: pytest
  Found existing installation: pytest 3.0.3
    Uninstalling pytest-3.0.3:
      Successfully uninstalled pytest-3.0.3
Successfully installed pytest-3.0.4
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(tsfresh-py2712) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py2712$
(tsfresh-py2712) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh$ git log | head
commit 06dd31ae522c91de8d3f7f394bab8ca061120f60
Author: Julius Neuffer <julius.neuffer@blue-yonder.com>
Date:   Thu Nov 10 13:11:10 2016 +0100

    Add check to ensure type of target vector y

    This resolves Issue #53

commit 8048ef44cc176ae46176573d9a4e83233a42c0d7
Merge: 7628807 d4deec5
(tsfresh-py2712) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh$ ../../../bin/python2.7 setup.py test
running test
running egg_info
writing requirements to tsfresh.egg-info/requires.txt
writing tsfresh.egg-info/PKG-INFO
writing top-level names to tsfresh.egg-info/top_level.txt
writing dependency_links to tsfresh.egg-info/dependency_links.txt
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'tsfresh.egg-info/SOURCES.txt'
running build_ext
=========================================================================== test session starts ===========================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.4, py-1.4.31, pluggy-0.4.0 -- /opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh/../../../bin/python2.7
cachedir: .cache
rootdir: /opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh, inifile: setup.cfg
plugins: xdist-1.15.0, cov-2.4.0
[gw0] linux2 Python 2.7.12 cwd: /opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh
[gw1] linux2 Python 2.7.12 cwd: /opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh
[gw2] linux2 Python 2.7.12 cwd: /opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh
[gw3] linux2 Python 2.7.12 cwd: /opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh
[gw0] Python 2.7.12 (default, Aug 20 2016, 09:15:25)  -- [GCC 4.8.4]
[gw1] Python 2.7.12 (default, Aug 20 2016, 09:15:25)  -- [GCC 4.8.4]
[gw2] Python 2.7.12 (default, Aug 20 2016, 09:15:25)  -- [GCC 4.8.4]
[gw3] Python 2.7.12 (default, Aug 20 2016, 09:15:25)  -- [GCC 4.8.4]
gw0 [107] / gw1 [107] / gw2 [107] / gw3 [107]
scheduling tests via LoadScheduling

tests/test_feature_significance.py::FeatureSignificanceTestCase::test_all_features_good
tests/test_feature_significance.py::FeatureSignificanceTestCase::test_all_features_bad
tests/test_feature_significance.py::FeatureSignificanceTestCase::test_binary_target_mixed_case
tests/test_feature_significance.py::FeatureSignificanceTestCase::test_binary_target_binary_features
[gw3] PASSED tests/test_feature_significance.py::FeatureSignificanceTestCase::test_all_features_bad

...
...
...

[gw2] PASSED tests/feature_extraction/test_feature_calculations.py::FeatureCalculationTestCase::test_binned_entropy Coverage.py warning: No data was collected.


---------- coverage: platform linux2, python 2.7.12-final-0 ----------
Name                                                 Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------------------------------
tsfresh/convenience/relevant_extraction.py              17      2      6      3    78%   44, 58, 43->44, 46->50, 55->58
tsfresh/examples/__init__.py                             3      0      0      0   100%
tsfresh/examples/har_dataset.py                         27     13      0      0    52%   45-50, 54-57, 62-65
tsfresh/examples/robot_execution_failures.py            46      9     16      2    76%   60-74, 94, 56->60, 93->94
tsfresh/feature_extraction/extraction.py                41      5     24      5    82%   73-75, 79, 98, 72->73, 78->79, 97->98, 183->181, 186->190
tsfresh/feature_extraction/feature_calculators.py      271      4     50      3    98%   271, 611, 823-824, 87->89, 270->271, 610->611
tsfresh/feature_extraction/settings.py                 117     12     68      8    87%   126-132, 158, 265, 270, 281, 308, 315, 75->exit, 157->158, 191->155, 264->265, 269->270, 278->281, 307->308, 312->315
tsfresh/feature_selection/__init__.py                    2      0      0      0   100%
tsfresh/feature_selection/feature_selector.py           66      5     24      1    91%   151-158, 149->151
tsfresh/feature_selection/selection.py                  23      6     12      5    63%   91, 94, 96, 98-101, 87->90, 90->91, 93->94, 95->96, 97->98
tsfresh/feature_selection/settings.py                   11      0      0      0   100%
tsfresh/feature_selection/significance_tests.py         62      0     16      0   100%
tsfresh/transformers/feature_augmenter.py               23      0      2      0   100%
tsfresh/transformers/feature_selector.py                21      0      8      0   100%
tsfresh/transformers/relevant_feature_augmenter.py      46      3     14      4    88%   183, 212, 226, 179->183, 187->190, 211->212, 222->226
tsfresh/utilities/dataframe_functions.py               103      2     84      2    98%   184, 262, 180->184, 255->262
------------------------------------------------------------------------------------------------
TOTAL                                                  879     61    324     33    91%


======================================================================= 107 passed in 22.51 seconds =======================================================================
(tsfresh-py2712) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py2712/apps/blue-yonder_master/tsfresh$
```

### Python-3.5.2

```
deactivate
cd
cd /opt/python_virtualenv/projects/tsfresh-py352/
source bin/activate
bin/pip3.5 install --upgrade pytest
cd apps/blue-yonder_master/tsfresh/
git log | head
../../../bin/python3.5 setup.py test


(tsfresh-py352) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py352$ bin/pip3.5 install --upgrade pytest
Collecting pytest
  Using cached pytest-3.0.4-py2.py3-none-any.whl
Requirement already up-to-date: py>=1.4.29 in ./lib/python3.5/site-packages (from pytest)
Installing collected packages: pytest
  Found existing installation: pytest 3.0.3
    Uninstalling pytest-3.0.3:
      Successfully uninstalled pytest-3.0.3
Successfully installed pytest-3.0.4
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(tsfresh-py352) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py352$ cd apps/blue-yonder_master/tsfresh/
(tsfresh-py352) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py352/apps/blue-yonder_master/tsfresh$ git log | head
commit 06dd31ae522c91de8d3f7f394bab8ca061120f60
Author: Julius Neuffer <julius.neuffer@blue-yonder.com>
Date:   Thu Nov 10 13:11:10 2016 +0100

    Add check to ensure type of target vector y

    This resolves Issue #53

commit 8048ef44cc176ae46176573d9a4e83233a42c0d7
Merge: 7628807 d4deec5
(tsfresh-py352) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py352/apps/blue-yonder_master/tsfresh$ ../../../bin/python3.5 setup.py test


...
...
...

[gw3] PASSED tests/transformers/test_relevant_feature_extractor.py::RelevantFeatureAugmenterTestCase::test_impute_works Coverage.py warning: No data was collected.


----------- coverage: platform linux, python 3.5.2-final-0 -----------
Name                                                 Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------------------------------
tsfresh/convenience/relevant_extraction.py              17      2      6      3    78%   44, 58, 43->44, 46->50, 55->58
tsfresh/examples/__init__.py                             3      0      0      0   100%
tsfresh/examples/har_dataset.py                         27     13      0      0    52%   45-50, 54-57, 62-65
tsfresh/examples/robot_execution_failures.py            46      9     16      2    76%   60-74, 94, 56->60, 93->94
tsfresh/feature_extraction/extraction.py                41      5     26      5    82%   73-75, 79, 98, 72->73, 78->79, 97->98, 183->181, 186->190
tsfresh/feature_extraction/feature_calculators.py      271      4     78      3    98%   271, 611, 823-824, 87->89, 270->271, 610->611
tsfresh/feature_extraction/settings.py                 117     12     90      8    88%   126-132, 158, 265, 270, 281, 308, 315, 75->exit, 157->158, 191->155, 264->265, 269->270, 278->281, 307->308, 312->315
tsfresh/feature_selection/__init__.py                    2      0      0      0   100%
tsfresh/feature_selection/feature_selector.py           66      5     28      1    91%   151-158, 149->151
tsfresh/feature_selection/selection.py                  23      6     12      5    63%   91, 94, 96, 98-101, 87->90, 90->91, 93->94, 95->96, 97->98
tsfresh/feature_selection/settings.py                   11      0      0      0   100%
tsfresh/feature_selection/significance_tests.py         62      0     16      0   100%
tsfresh/transformers/feature_augmenter.py               23      0      2      0   100%
tsfresh/transformers/feature_selector.py                21      0      8      0   100%
tsfresh/transformers/relevant_feature_augmenter.py      46      3     14      4    88%   183, 212, 226, 179->183, 187->190, 211->212, 222->226
tsfresh/utilities/dataframe_functions.py               103      2     86      2    98%   184, 262, 180->184, 255->262
------------------------------------------------------------------------------------------------
TOTAL                                                  879     61    382     33    91%


======================================================================= 107 passed in 21.75 seconds =======================================================================
(tsfresh-py352) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py352/apps/blue-yonder_master/tsfresh$
```


Hey... http://doc.pytest.org/en/latest/changelog.html

3.0.3

Got rid of AttributeError: 'Module' object has no attribute '_obj' exception in Python 3 (#1944). Thanks @axil for the PR.

Awesome @axil one less that was seen and could not be debugged :)